add deploy-14

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -11,7 +11,45 @@ permissions:
 
 jobs:
   ################### Build and test the application ###################
-  Build_test:
+  # Build_test:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #   - name: Configure AWS credentials
+  #     uses: aws-actions/configure-aws-credentials@v1
+  #     with:
+  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #       aws-region: ${{ secrets.AWS_REGION }}
+
+  #   - name: Set up Python 3.10
+  #     uses: actions/setup-python@v3
+  #     with:
+  #       python-version: "3.10"
+  #   - name: Install dependencies
+  #     run: |
+  #       python -m pip install --upgrade pip
+  #       pip install -r requirements.txt
+    
+  #   - name: Run tests
+  #     run:  nohup python app.py & 
+      
+  #   - name: Run curl command
+  #     run: curl http://localhost:5000
+
+  #   - name: Cleanup Python process
+  #     if: always()
+  #     run: |
+  #       # Kill by PID if file exists
+  #       if [ -f .pid ]; then
+  #         kill $(cat .pid) || true
+  #       fi
+  #       # Double check port is cleared
+  #       lsof -ti:5000 | xargs -r kill -9 || true
+      
+################## E2E Test ###################
+  E2E_test:
+    # needs: Build_test
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
@@ -21,38 +59,6 @@ jobs:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}
-
-    - name: Set up Python 3.10
-      uses: actions/setup-python@v3
-      with:
-        python-version: "3.10"
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
-    
-    - name: Run tests
-      run:  nohup python app.py & 
-      
-    - name: Run curl command
-      run: curl http://localhost:5000
-
-    - name: Cleanup Python process
-      if: always()
-      run: |
-        # Kill by PID if file exists
-        if [ -f .pid ]; then
-          kill $(cat .pid) || true
-        fi
-        # Double check port is cleared
-        lsof -ti:5000 | xargs -r kill -9 || true
-      
-################## E2E Test ###################
-  E2E_test:
-    needs: Build_test
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
     - name: give execute permission to the script
       run: chmod +x ./secret.sh
 
