add

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -30,15 +30,15 @@ jobs:
     - name: Run curl command
       run: curl http://localhost:5000
 
-    - name: Cleanup Python process
-      if: always()
-      run: |
-        # Kill by PID if file exists
-        if [ -f .pid ]; then
-          kill $(cat .pid) || true
-        fi
-        # Double check port is cleared
-        lsof -ti:5000 | xargs -r kill -9 || true
+    # - name: Cleanup Python process
+    #   if: always()
+    #   run: |
+    #     # Kill by PID if file exists
+    #     if [ -f .pid ]; then
+    #       kill $(cat .pid) || true
+    #     fi
+    #     # Double check port is cleared
+    #     lsof -ti:5000 | xargs -r kill -9 || true
       
 ################### E2E Test ###################
   E2E_test:
